# Generated by Django 4.1.7 on 2023-06-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vishome", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="contactdet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone", models.IntegerField(default=0)),
                ("emailid", models.EmailField(max_length=50)),
            ],
        ),
    ]
