# Generated by Django 4.1.7 on 2023-06-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vishome", "0002_contactdet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="proimg",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
